Repository DarkPacks/SevTech-Ages, pull requests merged in 2019-03, with the labels that each got.

#3577 Remove duplicate mods
  src/config/mputils/changelog.txt
Labels: Status: Accepted

#3505 Adding Nether-Ex Basalt to Chisel Basalt group
  src/config/mputils/changelog.txt
  src/scripts/crafttweaker/integrations/mods/chisel.zs
Labels: Status: Accepted

#3469 Create fr_FR.lang
  src/resources/sevtechages/lang/fr_FR.lang
Labels: Status: Accepted

#3028 Fix IE excavator not yielding geolosys clusters
  src/config/mputils/changelog.txt
  src/scripts/crafttweaker/integrations/mods/immersive/engineering/excavator.zs
  src/scripts/crafttweaker/oredict/ores.zs
Labels: Status: Accepted, Type: Bug

#3634 feat: stage Infused Crystal Pickaxe to Stage 2
  src/scripts/crafttweaker/staging/itemsAndRecipes/mods/astralsorcery.zs
Labels: Category: Staging
